"""empty message

Revision ID: 33081e868a95
Revises: 9fe933d6e27f
Create Date: 2021-04-25 22:35:11.012407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33081e868a95'
down_revision = '9fe933d6e27f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_address', sa.Column('address_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_address', 'address_name')
    # ### end Alembic commands ###
