"""empty message

Revision ID: 68c23c3d6586
Revises: 038c9a823a9f
Create Date: 2021-04-27 01:48:39.818203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c23c3d6586'
down_revision = '038c9a823a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'user_address', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'order_id')
    # ### end Alembic commands ###
