"""empty message

Revision ID: 78ef5e699a03
Revises: a23cc0182a88
Create Date: 2021-04-25 13:38:17.625817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ef5e699a03'
down_revision = 'a23cc0182a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('additional_info', sa.String(length=2000), nullable=True))
    op.add_column('products', sa.Column('description', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'additional_info')
    # ### end Alembic commands ###
