"""empty message

Revision ID: 7a613d9a030f
Revises: a492aba9c154
Create Date: 2021-01-05 01:34:56.720108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a613d9a030f'
down_revision = 'a492aba9c154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.drop_constraint('cart_user_id_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_product_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_images_product_id_fkey', 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_reviews_product_id_fkey', 'product_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'product_reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('user_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_types', ['user_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'user_type')
    op.drop_constraint('validation_tokens_user_id_fkey', 'validation_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'validation_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validation_tokens', type_='foreignkey')
    op.create_foreign_key('validation_tokens_user_id_fkey', 'validation_tokens', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('user_type', postgresql.ENUM('Buyer', 'Seller', 'Admin', name='usertypes'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_type_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'product_reviews', type_='foreignkey')
    op.create_foreign_key('product_reviews_product_id_fkey', 'product_reviews', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key('product_images_product_id_fkey', 'product_images', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_product_id_fkey', 'cart', 'products', ['product_id'], ['id'])
    op.create_foreign_key('cart_user_id_fkey', 'cart', 'users', ['user_id'], ['id'])
    op.drop_table('user_types')
    # ### end Alembic commands ###
