"""empty message

Revision ID: a23cc0182a88
Revises: 7a613d9a030f
Create Date: 2021-01-31 22:17:59.564280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23cc0182a88'
down_revision = '7a613d9a030f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'seller_id')
    # ### end Alembic commands ###
